language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="https://github.com/django/django/archive/1.7b4.zip"
  - DJANGO="https://github.com/django/django/archive/master.zip"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/archive/master.zip
install:
  - pip install south
  - pip install $DJANGO
  - pip install -e .
script:
  - ./runtests.sh
